### Cadastrar  usuário
POST http://localhost:3003/signup
Content-Type: application/json

{
    "name":"Ronald weasley ",
    "email":"rony@gmail.com",
    "password":"ruivo123",
    "role": "NORMAL"
}

### Logar usuario
POST http://localhost:3003/login
Content-Type: application/json

{
    "email":"rony@gmail.com",
    "password":"ruivo123"
}

### Pegar informações do seu perfil
GET http://localhost:3003/user/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZmZTU3NzFlLWI2NzctNGVkNy04OGRhLWRmMGNmMjg5OTFhNiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NDU3NDg3MDMsImV4cCI6MTY0NTc5MTkwM30.e-SXD6dO_Ns96XHIkZvGN5LyUuiCqQktJ8B_AKRxEmw
